import 'package:polkatalk/enums/language.dart';

Map<String, Language> get languageNamesInNativeFormat => {
      'English': Language.english,
      'Español': Language.spanish,
      'Français': Language.french,
      'Deutsch': Language.german,
      'Italiano': Language.italian,
      '日本語': Language.japanese,
      '中文': Language.chinese,
      'Русский': Language.russian,
      'العربية': Language.arabic,
      'Português': Language.portuguese,
      'हिन्दी': Language.hindi,
      'Bengali': Language.bengali,
      '한국어': Language.korean,
      'Tiếng Việt': Language.vietnamese,
      'Türkçe': Language.turkish,
      'Polski': Language.polish,
      'Bahasa Indonesia': Language.indonesian,
      'Nederlands': Language.dutch,
      'Svenska': Language.swedish,
      'Čeština': Language.czech,
      'עִבְרִית': Language.hebrew,
      'Magyar': Language.hungarian,
      'Dansk': Language.danish,
      'Українська': Language.ukrainian,
      'ภาษาไทย': Language.thai,
      'Ελληνικά': Language.greek,
      'Română': Language.romanian,
      'Norsk': Language.norwegian,
      'Slovenský': Language.slovak,
      'Suomi': Language.finnish,
      'Català': Language.catalan,
      'Hrvatski': Language.croatian,
      'Slovenščina': Language.slovenian,
      'Српски': Language.serbian,
      'Eesti': Language.estonian,
      'Lietuvių': Language.lithuanian,
      'Latviešu': Language.latvian,
      'Filipino': Language.filipino
    };
