import 'package:polkatalk/enums/language_name.dart';

List<Map<String, LanguageName>> get languageNamesInNativeFormat => [
      {'English': LanguageName.english},
      {'Español': LanguageName.spanish},
      {'Français': LanguageName.french},
      {'Deutsch': LanguageName.german},
      {'Italiano': LanguageName.italian},
      {'日本語': LanguageName.japanese},
      {'中文': LanguageName.chinese},
      {'Русский': LanguageName.russian},
      {'العربية': LanguageName.arabic},
      {'Português': LanguageName.portuguese},
      {'हिन्दी': LanguageName.hindi},
      {'Bengali': LanguageName.bengali},
      {'한국어': LanguageName.korean},
      {'Tiếng Việt': LanguageName.vietnamese},
      {'Türkçe': LanguageName.turkish},
      {'Polski': LanguageName.polish},
      {'Bahasa Indonesia': LanguageName.indonesian},
      {'Nederlands': LanguageName.dutch},
      {'Svenska': LanguageName.swedish},
      {'Čeština': LanguageName.czech},
      {'עִבְרִית': LanguageName.hebrew},
      {'Magyar': LanguageName.hungarian},
      {'Dansk': LanguageName.danish},
      {'Українська': LanguageName.ukrainian},
      {'ภาษาไทย': LanguageName.thai},
      {'Ελληνικά': LanguageName.greek},
      {'Română': LanguageName.romanian},
      {'Norsk': LanguageName.norwegian},
      {'Slovenský': LanguageName.slovak},
      {'Suomi': LanguageName.finnish},
      {'Català': LanguageName.catalan},
      {'Hrvatski': LanguageName.croatian},
      {'Slovenščina': LanguageName.slovenian},
      {'Српски': LanguageName.serbian},
      {'Eesti': LanguageName.estonian},
      {'Lietuvių': LanguageName.lithuanian},
      {'Latviešu': LanguageName.latvian},
      {'Filipino': LanguageName.filipino},
    ];
