import 'package:polkatalk/enums/profession.dart';

Map<String, Profession> get professions => {
      'Accountant': Profession.accountant,
      'Actor': Profession.actor,
      'Administrator': Profession.administrator,
      'Advertising Executive': Profession.advertisingExecutive,
      'Aerospace Engineer': Profession.aerospaceEngineer,
      'Agricultural Scientist': Profession.agriculturalScientist,
      'Air Traffic Controller': Profession.airTrafficController,
      'Architect': Profession.architect,
      'Artist': Profession.artist,
      'Astronomer': Profession.astronomer,
      'Attorney': Profession.attorney,
      'Auditor': Profession.auditor,
      'Automotive Technician': Profession.automotiveTechnician,
      'Baker': Profession.baker,
      'Banker': Profession.banker,
      'Bartender': Profession.bartender,
      'Biologist': Profession.biologist,
      'Bookkeeper': Profession.bookkeeper,
      'Bricklayer': Profession.bricklayer,
      'Business Analyst': Profession.businessAnalyst,
      'Carpenter': Profession.carpenter,
      'Chef': Profession.chef,
      'Chemist': Profession.chemist,
      'Civil Engineer': Profession.civilEngineer,
      'Cleaner': Profession.cleaner,
      'Coach': Profession.coach,
      'Computer Programmer': Profession.computerProgrammer,
      'Construction Worker': Profession.constructionWorker,
      'Consultant': Profession.consultant,
      'Content Writer': Profession.contentWriter,
      'Copywriter': Profession.copywriter,
      'Customer Service Representative':
          Profession.customerServiceRepresentative,
      'Dancer': Profession.dancer,
      'Data Analyst': Profession.dataAnalyst,
      'Database Administrator': Profession.databaseAdministrator,
      'Dentist': Profession.dentist,
      'Designer': Profession.designer,
      'Detective': Profession.detective,
      'Dietitian': Profession.dietitian,
      'Doctor': Profession.doctor,
      'Economist': Profession.economist,
      'Editor': Profession.editor,
      'Electrician': Profession.electrician,
      'Engineer': Profession.engineer,
      'Event Planner': Profession.eventPlanner,
      'Executive Assistant': Profession.executiveAssistant,
      'Fashion Designer': Profession.fashionDesigner,
      'Financial Advisor': Profession.financialAdvisor,
      'Firefighter': Profession.firefighter,
      'Fitness Trainer': Profession.fitnessTrainer,
      'Florist': Profession.florist,
      'Forensic Scientist': Profession.forensicScientist,
      'Freelancer': Profession.freelancer,
      'Fundraiser': Profession.fundraiser,
      'Game Developer': Profession.gameDeveloper,
      'Gardener': Profession.gardener,
      'Geologist': Profession.geologist,
      'Graphic Designer': Profession.graphicDesigner,
      'Hairdresser': Profession.hairdresser,
      'Historian': Profession.historian,
      'Hotel Manager': Profession.hotelManager,
      'HR Manager': Profession.hrManager,
      'Illustrator': Profession.illustrator,
      'Industrial Designer': Profession.industrialDesigner,
      'Information Security Analyst': Profession.informationSecurityAnalyst,
      'Insurance Agent': Profession.insuranceAgent,
      'Interior Designer': Profession.interiorDesigner,
      'Interpreter': Profession.interpreter,
      'Investment Banker': Profession.investmentBanker,
      'Journalist': Profession.journalist,
      'Judge': Profession.judge,
      'Lawyer': Profession.lawyer,
      'Librarian': Profession.librarian,
      'Life Coach': Profession.lifeCoach,
      'Linguist': Profession.linguist,
      'Logistics Manager': Profession.logisticsManager,
      'Makeup Artist': Profession.makeupArtist,
      'Management Consultant': Profession.managementConsultant,
      'Marketing Manager': Profession.marketingManager,
      'Massage Therapist': Profession.massageTherapist,
      'Mathematician': Profession.mathematician,
      'Mechanic': Profession.mechanic,
      'Medical Assistant': Profession.medicalAssistant,
      'Meteorologist': Profession.meteorologist,
      'Model': Profession.model,
      'Musician': Profession.musician,
      'Nurse': Profession.nurse,
      'Nutritionist': Profession.nutritionist,
      'Occupational Therapist': Profession.occupationalTherapist,
      'Operations Manager': Profession.operationsManager,
      'Optometrist': Profession.optometrist,
      'Painter': Profession.painter,
      'Paramedic': Profession.paramedic,
      'Personal Trainer': Profession.personalTrainer,
      'Pharmacist': Profession.pharmacist,
      'Photographer': Profession.photographer,
      'Physicist': Profession.physicist,
      'Pilot': Profession.pilot,
      'Plumber': Profession.plumber,
      'Police Officer': Profession.policeOfficer,
      'Politician': Profession.politician,
      'Professor': Profession.professor,
      'Project Manager': Profession.projectManager,
      'Psychologist': Profession.psychologist,
      'Public Relations Specialist': Profession.publicRelationsSpecialist,
      'Real Estate Agent': Profession.realEstateAgent,
      'Receptionist': Profession.receptionist,
      'Recruiter': Profession.recruiter,
      'Research Scientist': Profession.researchScientist,
      'Sales Representative': Profession.salesRepresentative,
      'Scientist': Profession.scientist,
      'Secretary': Profession.secretary,
      'Social Media Manager': Profession.socialMediaManager,
      'Software Engineer': Profession.softwareEngineer,
      'Solar Panel Installer': Profession.solarPanelInstaller,
      'Speech Therapist': Profession.speechTherapist,
      'Sports Coach': Profession.sportsCoach,
      'Statistician': Profession.statistician,
      'Surgeon': Profession.surgeon,
      'Surveyor': Profession.surveyor,
      'Systems Analyst': Profession.systemsAnalyst,
      'Teacher': Profession.teacher,
      'Technical Writer': Profession.technicalWriter,
      'Translator': Profession.translator,
      'Travel Agent': Profession.travelAgent,
      'Truck Driver': Profession.truckDriver,
      'UX Designer': Profession.uxDesigner,
      'Veterinarian': Profession.veterinarian,
      'Video Editor': Profession.videoEditor,
      'Virtual Assistant': Profession.virtualAssistant,
      'Waiter': Profession.waiter,
      'Waitress': Profession.waitress,
      'Web Developer': Profession.webDeveloper,
      'Welder': Profession.welder,
      'Writer': Profession.writer,
      'Yoga Instructor': Profession.yogaInstructor,
      'Zoologist': Profession.zoologist,
    };
