enum LanguageNames {
  english,
  spanish,
  french,
  german,
  italian,
  japanese,
  chinese,
  russian,
  arabic,
  portuguese,
  hindi,
  bengali,
  korean,
  vietnamese,
  turkish,
  polish,
  indonesian,
  dutch,
  swedish,
  czech,
  hebrew,
  hungarian,
  danish,
  ukrainian,
  thai,
  greek,
  romanian,
  norwegian,
  slovak,
  finnish,
  catalan,
  croatian,
  slovenian,
  serbian,
  estonian,
  lithuanian,
  latvian,
  filipino,
}

List<Map<String, LanguageNames>> get languageNamesInNativeFormat => [
      {'English': LanguageNames.english},
      {'Español': LanguageNames.spanish},
      {'Français': LanguageNames.french},
      {'Deutsch': LanguageNames.german},
      {'Italiano': LanguageNames.italian},
      {'日本語': LanguageNames.japanese},
      {'中文': LanguageNames.chinese},
      {'Русский': LanguageNames.russian},
      {'العربية': LanguageNames.arabic},
      {'Português': LanguageNames.portuguese},
      {'हिन्दी': LanguageNames.hindi},
      {'Bengali': LanguageNames.bengali},
      {'한국어': LanguageNames.korean},
      {'Tiếng Việt': LanguageNames.vietnamese},
      {'Türkçe': LanguageNames.turkish},
      {'Polski': LanguageNames.polish},
      {'Bahasa Indonesia': LanguageNames.indonesian},
      {'Nederlands': LanguageNames.dutch},
      {'Svenska': LanguageNames.swedish},
      {'Čeština': LanguageNames.czech},
      {'עִבְרִית': LanguageNames.hebrew},
      {'Magyar': LanguageNames.hungarian},
      {'Dansk': LanguageNames.danish},
      {'Українська': LanguageNames.ukrainian},
      {'ภาษาไทย': LanguageNames.thai},
      {'Ελληνικά': LanguageNames.greek},
      {'Română': LanguageNames.romanian},
      {'Norsk': LanguageNames.norwegian},
      {'Slovenský': LanguageNames.slovak},
      {'Suomi': LanguageNames.finnish},
      {'Català': LanguageNames.catalan},
      {'Hrvatski': LanguageNames.croatian},
      {'Slovenščina': LanguageNames.slovenian},
      {'Српски': LanguageNames.serbian},
      {'Eesti': LanguageNames.estonian},
      {'Lietuvių': LanguageNames.lithuanian},
      {'Latviešu': LanguageNames.latvian},
      {'Filipino': LanguageNames.filipino},
    ];
